@startuml cl_exasol_driver_lua
!include ../clean.skin

title: Exasol Driver for Lua

package luasql.exasol {
    '[dsn -> req~luasql-entry-point~1 >> impl,utest]
    class entry {
        + exasol()
    }
    '[dsn -> req~luasql-environment~1 >> impl,utest,itest]
    class Environment {
        + connect(sourcename, username, password): Connection
        + close(): boolean
    }
    '[dsn -> req~luasql-connection~1 >> impl,utest,itest]
    class Connection {
        + execute(statement): Cursor
        + commit(): boolean
        + rollback(): boolean
        + setautocommit(boolean): boolean
        + close(): boolean
    }
    '[dsn -> req~luasql-cursor~1 >> impl,utest,itest]
    class Cursor {
        + close(): boolean
        + fetch([table[,modestring]]): table
        + getcolnames(): list (table)
        + getcoltypes(): list (table)
    }
    package websocket {
        class Websocket {
            +connect(url): Websocket
            +send_raw(payload, ignore_response): string
            +close(): boolean
        }
        class ExasolWebsocket {
            +connect(url): ExasolWebsocket
            +send_login_command(): response, error
            +send_login_credentials(username, encrypted_password): response, error
            +send_disconnect(): error
            +send_execute(statement): response, error
            -_send_json(payload, ignore_response): response, error
            +close(): boolean
        }
        class WebsocketDatahandler {
            +handle_data(socket, opcode, message): void
            +expect_data(): void
            +expected_data_received(): void
            +get_data(): string
            +has_received_data(): boolean
        }
        ExasolWebsocket .l.> Websocket : use
        Websocket .l.> togglebits.luws : use
        Websocket .l.> WebsocketDatahandler : use
    }
}
package togglebits <<external>> {
    class luws {
        +wsopen(url, message_handler, options): socket
        +wssend(socket, opcode, data)
        +wsreceive(socket)
        +wsclose(socket)
    }
}
entry -> Environment : create
Environment o-- Connection : +Composition
Connection o-- Cursor : +Composition
'Environment -> ExasolWebsocket : create
Connection .l.> ExasolWebsocket : use
Cursor .l.> ExasolWebsocket : use

url of togglebits is [[https://github.com/toggledbits/LuWS]]
url of togglebits.luws is [[https://github.com/toggledbits/LuWS]]

@enduml