@startuml seq_close
!include ../clean.skin

title: Closing the Database Connection

participant "Client Code" as client <<external>>
box "Exasol Driver for Lua"
    participant Environment as env << (C,#ADD1B2) >>
    participant Connection as conn << (C,#ADD1B2) >>
    participant Cursor as cur << (C,#ADD1B2) >>
    participant ExasolWebsocket as exaws << (C,#ADD1B2) >>
    participant Websocket as ws << (C,#ADD1B2) >>
    participant "LuWS Socket" as luws <<Third party library>>
end box
participant "Exasol Database" as db

activate client
activate env
activate conn
activate cur
activate exaws
activate ws
activate luws
activate db

client -> env : close()
loop for all connections
    env -> conn : close()
    loop for all cursors
        conn -> cur : close()
        alt Cursor with\nresultset
            cur -> exaws : send_close_\nresultset()
            exaws -> ws : send_raw(payload)
            ws -> luws : wssend(socket,\npayload)
            luws -> db
            db --> luws
            luws --> ws
            ws --> exaws
            exaws --> cur
        end
        cur --> conn
        destroy cur
    end
    conn -> exaws : send_disconnect()
    exaws -> ws : send_raw(payload)
    ws -> luws : wssend(socket,\npayload)
    luws -> db
    db --> luws
    luws --> ws
    ws --> exaws
    exaws --> conn
    conn -> exaws : close()
    exaws -> ws : close()
    ws -> luws : wsclose(socket)
    luws -> luws : Close socket
    destroy luws
    luws --> ws
    ws --> exaws
    destroy ws
    exaws --> conn
    destroy exaws
    conn --> env
    destroy conn
end
env --> client
destroy env

@enduml