@startuml seq_environment_close
!include ../clean.skin

title: Closing the Environment

participant "Client Code" as client <<external>>
box "Exasol Driver for Lua"
    participant Environment as env << (C,#ADD1B2) >>
    participant Connection as conn << (C,#ADD1B2) >>
    participant ExasolWebsocket as exaws << (C,#ADD1B2) >>
    participant Websocket as ws << (C,#ADD1B2) >>
    participant "LuWS Socket" as luws <<Third party library>>
end box
participant "Exasol Database" as db

activate client
activate db

client -> env : close()
activate env
loop for all connections
    env -> conn : close()
    activate conn
    ref over conn, db: Close connection and its cursors
    conn --> env
    destroy conn
end
env --> client: Success (boolean)
destroy env

@enduml