@startuml seq_environment_close
!include ../clean.skin

participant "Client Code" as client <<external>>
box "Exasol Driver for Lua"
    participant Environment as env << (C,#ADD1B2) >>
    participant Connection as conn << (C,#ADD1B2) >>
end box
participant "Exasol Database" as db

activate client
activate db

' [dsn -> req~luasql-environment-close~1 >> impl,itest]
client -> env : close()
activate env
loop for all connections
    env -> conn : closed
    activate conn
    conn -->> env: is closed
    deactivate conn
end
alt at least one connection is not closed
    env -->> client: false
else all connections are closed
    env -->> client: true
    destroy env
end

@enduml