@startuml seq_execute_statement
!include ../clean.skin

title: Executing Statements and fetching results

participant "Client Code" as client <<external>>
participant Connection as conn << (C,#ADD1B2) >>
participant Cursor as cur << (C,#ADD1B2) >>
participant Websocket as ws << (C,#ADD1B2) >>
participant "Exasol Database" as db

activate client
activate db
client -> conn: execute(statement)
activate conn
conn -> ws: execute
activate ws
group Websocket Request/Response
    note over ws: See details in separate diagram
    ws -> db: execute
    activate db
    db -> db: Execute query
    db --> ws
    deactivate db
end
ws --> conn: Resultset or resultset handle
deactivate ws
create cur
conn -> cur: create()
conn --> client
deactivate conn
loop Fetch results until all rows fetched
    client -> cur: fetch()
    activate cur
    alt If DB has returned a resultset handle\nand no more rows available in local list
        cur -> ws : fetch(resultset_handle)
        activate ws
        ws -> db : fetch(resultset_handle)
        activate db
        db --> ws
        deactivate db
        ws --> cur
        deactivate ws
        cur -> cur : Store data in local list
    end
    cur -> cur : Get next row from local list
    cur --> client
    deactivate cur
end
group Close cursor
    client -> cur : close()
    activate cur
    alt No resultset handle
        note right of cur: Nothing to do when no resultset is used
    else Result set handle, more than 1000 rows
        cur -> ws : close resultset
        activate ws
        ws -> db : close resultset
        activate db
        db --> ws
        deactivate db
        ws --> cur
        deactivate ws
    end
    cur --> client
    deactivate cur
    destroy cur
    deactivate cur
end

@enduml