@startuml seq_connection
!include ../clean.skin

title: Create Connection

participant "Client Code" as client <<external>>
participant entry
participant Environment as env
participant Connection as conn
participant Cursor as cur
participant Websocket as ws
participant "Exasol Database" as db

activate db
client -> entry: exasol()
entry -> env: Create
activate env
client <-- entry: Environment
client -> env: connect()
' [dsn -> req~connect-with-username-password~1 >> impl,utest,itest]
group Login
    env -> ws: Connect
    activate ws
    ws -> db: Connect
    env -> ws: Login command
    ws -> db: Login command
    db --> ws: Login response
    ws --> env: Login response
    env -> env: Encrypt password
    env -> ws: Username and encrypted password
    ws -> db: Username and encrypted password
    db --> ws: Session ID
    ws --> env: Session ID
    env -> conn: Create with Session ID
    activate conn
end
activate conn
client <-- env: Connection


group Close
    client -> env: close()
    env -> conn: close()
    conn -> cur: close()
    deactivate cur
    deactivate conn
    deactivate env
end

@enduml