@startuml seq_environment_connect
!include ../clean.skin

participant "Client Code" as client <<external>>
box "Exasol Driver for Lua"
participant "luasqlexasol\ndriver"  as entry
participant Environment as env << (C,#ADD1B2) >>
participant Connection as conn << (C,#ADD1B2) >>
participant ExasolWebsocket as ws << (C,#ADD1B2) >>
end box
participant "Exasol Database" as db

activate client
activate db
client -> entry: exasol()
activate entry
create env
entry -> env: create()
client <-- entry: Environment
deactivate entry
client -> env: connect(host_and_port, user, password)
activate env
' [dsn -> req~connect-with-username-password~1 >> impl,utest,itest]
create ws
env -> ws: connect(url)
activate ws
ws -> db: Connect
activate db
db --> ws
deactivate db
ws --> env
deactivate ws
group Login command and send credentials
    env -> ws: send_login_command()
    activate ws
    ws -> db: Login command
    activate db
    db -> db : Generate public key
    db --> ws: Login response\nincl. public key
    deactivate db
    ws --> env: Public key
    deactivate ws
    env -> env: Encrypt password\nwith public key
    env -> ws: send_login_credentials(username,\nencrypted_password)
    activate ws
    ws -> db: Credentials
    activate db
    db -> db: Validate credentials
    db --> ws: Session ID
    deactivate db
    ws --> env: Session ID
    deactivate ws
    create conn
    env -> conn: create(session_id)
end
client <-- env: connection
deactivate env
ref over client, conn: Use connection, e.g. connection:execute(statement)
@enduml