@startuml seq_connection_setautocommit
!include ../clean.skin

participant "Client Code" as client <<external>>
participant Connection as conn << (C,#ADD1B2) >>
participant ExasolWebsocket as ws << (C,#ADD1B2) >>
participant "Exasol Database" as db

activate client
activate db

' [dsn -> req~luasql-connection-setautocommit~1 >> impl,utest,itest]
client -> conn: setautocommit(boolean)
activate conn
conn -> ws : send_set_attribute(\nautocommit=true/false)
activate ws
ws -> db
activate db
db -> db : Update autocommit\nstatus for session
db --> ws
deactivate db
ws -> conn
deactivate ws
conn --> client: Success (boolean)
deactivate conn

@enduml