@startuml seq_connection_rollback
!include ../clean.skin

participant "Client Code" as client <<external>>
participant Connection as conn << (C,#ADD1B2) >>
participant ExasolWebsocket as ws << (C,#ADD1B2) >>
participant "Exasol Database" as db

activate client
activate db

' [dsn -> req~luasql-connection-rollback~1 >> impl,utest,itest]
client -> conn: rollback()
activate conn
conn -> ws: send_execute("ROLLBACK")
activate ws

ws -> db: execute
activate db
db -> db: Commit
db -->> ws
deactivate db
ws -->> conn
conn -->> client: Success (boolean)
deactivate conn

@enduml