name: Broken Links Checker

on:
  schedule:
    - cron: "0 5 * * 0"
  push:
    branches:
      - main
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Configure broken links checker
        run: |
          mkdir -p ./target
          echo '{"aliveStatusCodes": [429, 200], "ignorePatterns": [' \
               '{"pattern": "^https?://(www|dev).mysql.com/"},' \
               '{"pattern": "^https?://(www.)?opensource.org"}' \
               ']}' > ./target/broken_links_checker.json
      - uses: tcort/markdown-link-check@275c27c5035a5b4a656fe0e21a4c1403c118c767 # 3.15.0
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: ./target/broken_links_checker.json
