name: "Build and test Lua project"
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install luarocks
          # Build dependencies (will be move to rockspec with LuaRocks 3)
          sudo luarocks install luacheck
          sudo luarocks install luacov
          sudo luarocks install luacov-coveralls
          sudo luarocks install LuaUnit
          sudo apt install shellcheck
      - name: Print versions
        run: |
          lua -v
          luarocks --version
          luarocks path
      - uses: actions/checkout@v2
      - name: Validate tools
        run: shellcheck --check-sourced --severity=style tools/runtests.sh tools/trace-requirements.sh
      - name: "Build"
        run: |
          luarocks make --local
      - name: Run static code analysis
        run: tools/runluacheck.sh

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: 'exasol-driver-lua'
      - name: Checkout integration test docker environment
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: 'exasol/integration-test-docker-environment'
          path: 'integration-test-docker-environment'
      - name: Spawn Exasol environment
        run: |
          ./start-test-env spawn-test-environment --environment-name test --database-port-forward 8563 --deactivate-database-setup
        working-directory: integration-test-docker-environment
      - name: Run integration tests
        run: tools/runtests.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out

  trace-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Trace requirements
        run: ./tools/trace-requirements.sh
