name: "Build and test Lua project"
on: [push]
jobs:

  build:
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
       fail-fast: true
       matrix:
          lua_version: [5.3]
    name: "Build with Lua ${{ matrix.lua_version }}"
    runs-on: ubuntu-latest
    steps:

      - name: Cache Luarocks dependencies
        uses: actions/cache@v2
        with:
          path: ~/.luarocks
          key: ${{ runner.os }}-lua-${{ matrix.lua_version }}-${{ hashFiles('*.rockspec') }}
          restore-keys: |
            ${{ runner.os }}-lua-
            ${{ runner.os }}-lua-${{ matrix.lua_version }}-
            ${{ runner.os }}-lua-${{ matrix.lua_version }}-${{ hashFiles('*.rockspec') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install lua${{ matrix.lua_version }} liblua${{ matrix.lua_version }} lua-any shellcheck
          wget http://http.us.debian.org/debian/pool/main/l/luarocks/luarocks_3.8.0+dfsg1-1_all.deb
          sudo dpkg -i luarocks_3.8.0+dfsg1-1_all.deb

      - name: Print versions
        run: |
          lua -v
          luarocks --version
          luarocks path

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout integration test docker environment
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: 'exasol/integration-test-docker-environment'
          path: 'integration-test-docker-environment'

      - name: Install Lua dependencies
        run: |
          luarocks install luacheck
          luarocks install --deps-only *.rockspec

      - name: Validate tools
        run: shellcheck --check-sourced --severity=style tools/runtests.sh tools/trace-requirements.sh

      - name: "Build"
        run: luarocks make --local

      - name: Run static code analysis
        run: tools/runluacheck.sh

      - name: Spawn Exasol environment
        run: |
          ./start-test-env spawn-test-environment --environment-name test --database-port-forward 8563 --deactivate-database-setup
        working-directory: integration-test-docker-environment

      - name: Run integration tests
        run: |
          source $GITHUB_WORKSPACE/integration-test-docker-environment/.build_output/cache/environments/test/environment_info.sh
          EXASOL_HOST=$ENVIRONMENT_DATABASE_HOST \
            EXASOL_PORT=$ENVIRONMENT_DATABASE_DB_PORT \
            EXASOL_USER=sys EXASOL_PASSWORD=exasol \
            tools/runtests.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out

  trace-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Trace requirements
        run: ./tools/trace-requirements.sh
