name: Publish API documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Lua
        uses: leafo/gh-actions-lua@6919171ccf181b826f44b9bca76307b577217377 # v13.0.0
        with:
          luaVersion: "5.4"

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@35d062def313a7699a0d513e996bcf4352f05389 # v6.1.0
        with:
          luaRocksVersion: "3.13.0"

      - name: Install Tools
        run: |
          luarocks install --local ldoc

      - name: Generate API documentation
        run: |
          ./tools/build-docs.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./target/ldoc

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
